- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponShotgunKammererBeanbag
  result: WeaponShotgunKammererBeanbag
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponBlasterPistol
  result: WeaponBlasterPistol
  materials:
    Steel: 1000
    Glass: 400
    Plastic: 300
    Gold: 10

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponBlasterCannon
  result: WeaponBlasterCannon
  materials:
    Steel: 2000
    Plastic: 1000
    Gold: 750

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponBlasterMagnum
  result: WeaponBlasterMagnum
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponShotgunEnforcerBeanbag
  result: WeaponShotgunEnforcerBeanbag
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: FullAutoConversionKit
  result: FullAutoConversionKit
  materials:
    Steel: 500
    Glass: 200
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: HyperBurstConversionKit
  result: HyperBurstConversionKit
  materials:
    Steel: 500
    Glass: 200
    Plastic: 500

- type: latheRecipe
  parent: BaseToolRecipe
  id: PRIbarPlusConversionKit
  result: PRIbarPlusConversionKit
  materials:
    Steel: 500
    Plastic: 500

- type: latheRecipe
  id: PowerCellBlaster
  result: PowerCellBlaster
  categories:
  - Ammo
  completetime: 6
  materials:
    Steel: 300
    Glass: 300
    Plastic: 100
    Gold: 10

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineLPistolEmpty
  result: MagazineLPistolEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLPistol
  result: MagazineLPistol
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLPistolPractice
  result: MagazineLPistolPractice
  materials:
    Steel: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLPistolUranium
  result: MagazineLPistolUranium
  materials:
    Steel: 50
    Plastic: 100
    Uranium: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLPistolIncendiary
  result: MagazineLPistolIncendiary
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLPistol
  result: MagazineBoxLPistol
  materials:
    Steel: 1000

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLPistolIncendiary
  result: MagazineBoxLPistolIncendiary
  materials:
    Plastic: 1000

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLPistolPractice
  result: MagazineBoxLPistolPractice
  materials:
    Steel: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLPistolUranium
  result: MagazineBoxLPistolUranium
  materials:
    Plastic: 500
    Uranium: 1000

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineDMREmpty
  result: MagazineDMREmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineDMR
  result: MagazineDMR
  materials:
    Steel: 565

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineDMRUranium
  result: MagazineDMRUranium
  materials:
    Steel: 25
    Plastic: 360
    Uranium: 360

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineDMRIncendiary
  result: MagazineDMRIncendiary
  materials:
    Steel: 25
    Plastic: 540

- type: latheRecipe
  id: BriefcaseSteelRecipe
  result: BriefcaseSteel
  completetime: 4
  materials:
    Steel: 500
    Plasma: 200
    Cloth: 100
    Plastic: 100